// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.DAL;

#nullable disable

namespace WebShop.DAL.Migrations
{
    [DbContext(typeof(AutoShopDbContext))]
    [Migration("20260226155020_AddInStockProduct")]
    partial class AddInStockProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShop.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CAT-001",
                            Description = "Desktop računari i radne stanice.",
                            Name = "Računari"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CAT-002",
                            Description = "Prenosni računari svih kategorija.",
                            Name = "Laptopovi"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CAT-003",
                            Description = "Procesori, matične ploče, RAM, grafičke kartice i ostale komponente.",
                            Name = "Komponente"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CAT-004",
                            Description = "Tastature, miševi, monitori, slušalice i ostala periferija.",
                            Name = "Periferija"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebShop.DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "PROD-001",
                            Description = "Intel Core i7-13700K, 32GB DDR5, RTX 4070, 1TB NVMe SSD.",
                            InStock = true,
                            Name = "Gaming Desktop PC",
                            Price = 1850m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "PROD-002",
                            Description = "Intel Core i5-12400, 16GB DDR4, 512GB SSD, Windows 11 Pro.",
                            InStock = true,
                            Name = "Office Desktop PC",
                            Price = 750m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Code = "PROD-003",
                            Description = "AMD Ryzen 7 7745H, 16GB RAM, RTX 4060, 1TB SSD, 144Hz ekran.",
                            InStock = true,
                            Name = "Gaming Laptop 15.6\"",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Code = "PROD-004",
                            Description = "Intel Core i5-1335U, 16GB RAM, 512GB SSD, Full HD IPS ekran.",
                            InStock = true,
                            Name = "Business Laptop 14\"",
                            Price = 850m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Code = "PROD-005",
                            Description = "NVIDIA GeForce RTX 4070, 12GB GDDR6X, PCIe 4.0.",
                            InStock = true,
                            Name = "Grafička kartica RTX 4070",
                            Price = 620m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Code = "PROD-006",
                            Description = "24-jezgarni procesor, do 5.8 GHz Turbo, LGA1700 socket.",
                            InStock = true,
                            Name = "Procesor Intel Core i9-13900K",
                            Price = 430m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Code = "PROD-007",
                            Description = "Kingston Fury Beast 32GB (2x16GB) DDR5, CL32.",
                            InStock = true,
                            Name = "RAM 32GB DDR5 6000MHz",
                            Price = 140m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Code = "PROD-008",
                            Description = "IPS panel, 2560x1440, 165Hz, 1ms GTG, HDR400, FreeSync.",
                            InStock = true,
                            Name = "Gaming Monitor 27\" 165Hz",
                            Price = 380m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Code = "PROD-009",
                            Description = "TKL raspored, Cherry MX Red switches, RGB pozadinsko osvjetljenje.",
                            InStock = true,
                            Name = "Mehanička tastatura",
                            Price = 95m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Code = "PROD-010",
                            Description = "25600 DPI senzor, 7 programabilnih tastera, RGB, 70g težina.",
                            InStock = true,
                            Name = "Gaming miš",
                            Price = 55m
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            IsActive = true,
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@test.com",
                            IsActive = true,
                            Password = "user123",
                            RoleId = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.HasOne("WebShop.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShop.DAL.Models.OrderItem", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Product", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShop.DAL.Models.User", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
