// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.DAL;

#nullable disable

namespace WebShop.DAL.Migrations
{
    [DbContext(typeof(AutoShopDbContext))]
    [Migration("20260528142421_AddInStockToProduct")]
    partial class AddInStockToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShop.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CAT-001",
                            Description = "Putničke limuzine i sedan automobili.",
                            Name = "Sedani"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CAT-002",
                            Description = "Sportsko-terenska vozila i četvorotokaši.",
                            Name = "SUV i terenski"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CAT-003",
                            Description = "Sportski i super-sports automobili visokih performansi.",
                            Name = "Sportski automobili"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CAT-004",
                            Description = "Karavan vozila, minivani i kombi vozila.",
                            Name = "Karavan i minivan"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebShop.DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "PROD-001",
                            Description = "Elegantna limuzina, 2.0L dizel, 190KS, automatski menjač, kamera za parkiranje.",
                            InStock = true,
                            Name = "BMW Serija 5 520d",
                            Price = 52000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "PROD-002",
                            Description = "Hibridni pogon, 218KS, premium oprema, Apple CarPlay, adaptive cruise control.",
                            InStock = true,
                            Name = "Toyota Camry 2.5 Hybrid",
                            Price = 38500m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Code = "PROD-003",
                            Description = "Luksuzni SUV, 3.0L dizel, 272KS, 4MATIC, panoramski krov, 7 sedišta.",
                            InStock = true,
                            Name = "Mercedes-Benz GLE 350d",
                            Price = 75000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Code = "PROD-004",
                            Description = "Popularni porodični SUV, 150KS, DSG menjač, Digital Cockpit, LED svetla.",
                            InStock = true,
                            Name = "Volkswagen Tiguan 2.0 TDI",
                            Price = 42000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Code = "PROD-005",
                            Description = "Kultni sportski automobil, 3.0L biturbo, 450KS, PDK, Sport Chrono paket.",
                            InStock = true,
                            Name = "Porsche 911 Carrera 4S",
                            Price = 135000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Code = "PROD-006",
                            Description = "Sportski coupe, 3.0L biturbo, 510KS, M xDrive, Track mode, karbonski krov.",
                            InStock = true,
                            Name = "BMW M4 Competition",
                            Price = 89000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Code = "PROD-007",
                            Description = "Praktičan karavan, 120KS, veliki prtljažnik 608L, Android Auto, sigurnosni sistemi.",
                            InStock = true,
                            Name = "Ford Focus Karavan 1.5 EcoBlue",
                            Price = 28500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Code = "PROD-008",
                            Description = "Moderan 7-sedišni minivan, 158KS, EDC menjač, panoramski krov, Google sistemi.",
                            InStock = true,
                            Name = "Renault Espace 1.3 TCe",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Code = "PROD-009",
                            Description = "Prestižna limuzina, 2.0L turbo, 245KS, quattro, Matrix LED, virtualna tabla.",
                            InStock = true,
                            Name = "Audi A6 45 TFSI",
                            Price = 65000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Code = "PROD-010",
                            Description = "Električni automobil, domet 602km, Autopilot, 0-100 km/h za 4.4s, AWD.",
                            InStock = true,
                            Name = "Tesla Model 3 Long Range",
                            Price = 48000m
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            IsActive = true,
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@test.com",
                            IsActive = true,
                            Password = "user123",
                            RoleId = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.HasOne("WebShop.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShop.DAL.Models.OrderItem", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Product", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShop.DAL.Models.User", b =>
                {
                    b.HasOne("WebShop.DAL.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebShop.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
